% model_test_1.m  Find rendering scale constant c for Lambertian materials
%                 (see equation (2) in main text)

% See readme_appendix_b.txt for details about how to run this test.

clear; clc;

% addpath ../tools
addpath tools

% load data generated by Unity project model_test with a Lambertian
% material and no tonemapping
data = readtable('data_L1_T0_F0_A1_S00100_M1.txt');

% tranform table into model parameters
m = [ data.m_r data.m_g data.m_b ];
d = [ data.d_r data.d_g data.d_b ];
a = [ data.a_r data.a_g data.a_b ];
v = [ data.v_r data.v_g data.v_b ];
i_d = data.i_d;
i_a = data.i_a;
l = [ data.l_x data.l_y data.l_z ];
n = [ data.n_x data.n_y data.n_z ];
costheta = sum(l .* n,2);

% apply Lambertian rendering model to get predicted rendered color
% coordinates u_k, without rendering scale constant c
u_mod_hat = srgb(m) .* ( i_d .* srgb(d) .* max(costheta, 0) / pi + i_a .* a );

% apply sRGB nonlinearity to get actual rendered color coordinates u_k
u = srgb(v);

% discard values outside [ 0, 0.95 ]
k = u < 0 | u > 0.95 | u_mod_hat < 0 | u_mod_hat > 0.95;
u(k) = NaN;
u_mod_hat(k) = NaN;

% plot predicted rendered color coordinates u_k, without scale constant c,
% against actual coordinates
xylim = [ 0 1.1 ];
plot(xylim, xylim, 'k-');
hold on
hr = plot(u(:,1), u_mod_hat(:,1), 'ro', 'MarkerFaceColor', 'r', 'MarkerSize', 10);
hg = plot(u(:,2), u_mod_hat(:,2), 'go', 'MarkerFaceColor', 'g', 'MarkerSize', 10);
hb = plot(u(:,3), u_mod_hat(:,3), 'bo', 'MarkerFaceColor', 'b', 'MarkerSize', 10);
hold off
axis square
axis([ xylim xylim ]);
xlabel 'actual u_k'
ylabel 'predicted u_k'
legend([hr hg hb], 'red channel', 'green channel', 'blue channel', 'location', 'northwest', 'box', 'off', 'AutoUpdate', 'off');
set(gca,'FontSize',18);

% find regression slope of above plot
r = regress(u_mod_hat(:), u(:));

% add regression line to plot
hold on
plot(xlim, r*xlim, 'r-');
hold off
% print -dpdf model_test_1.pdf

% the scale constant that will adjust the predicted renderd color
% coordinates u_k so that they fall on the line y=x is the inverse
% of the regression slope
c = 1/r;
fprintf('rendering model scale constant: c = %.3f\n', c);
